<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>This suits contains all the test cases of edit media page</description>
   <name>Edit_Media</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>59fad948-0469-4041-baa6-d29119fb61e2</testSuiteGuid>
   <testCaseLink>
      <guid>93b931b1-0d7f-4710-999a-7ebc8680e41f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_valid_creds</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8607b6b2-52ac-499e-93a6-60585e23afc8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/URL/url</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>668a9593-35e3-4332-b08d-be3be26289ba</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/TD_valid_creds</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8607b6b2-52ac-499e-93a6-60585e23afc8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>1a78a52c-11ab-432e-982a-c9740cbf0427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>668a9593-35e3-4332-b08d-be3be26289ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>cfdf9da2-de49-4845-9524-42a24b2cc088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>668a9593-35e3-4332-b08d-be3be26289ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>02f7527c-85b4-40e0-b654-8c281ddff16e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0fcad20-3661-4f0a-96df-79de14b99009</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Update_date</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef242e01-95fe-491a-ad8c-7b2cec1e6084</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cf6fa5a-783d-4f6e-b4a3-2d3c2a586692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf40ac9c-fa3c-4a1f-a16f-56b2cad960f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>694e8328-263c-4cc3-ae05-8c432f1d763e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Update_series</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>09dd2bbe-c26b-4284-a676-20230986ca76</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd5d110e-0874-413e-b230-7d407d4c2075</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>060eea4c-1175-49d8-98f3-7fdbc9e17291</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>09dd2bbe-c26b-4284-a676-20230986ca76</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Series textName</value>
         <variableId>aea9e073-bd8a-4f79-852e-d8dce87711ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1756119-73e5-4159-8192-46a12caa7aaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Update_speaker</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1b0287b4-07ea-4742-9d7e-fabc8e7a6c14</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f759f586-1d89-4c9e-bf8a-6a6fc66c2350</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c9bc7aa-fa0b-4bc9-9679-80146240d4bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1b0287b4-07ea-4742-9d7e-fabc8e7a6c14</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SpeakerName</value>
         <variableId>bd4bde93-ae50-4936-9791-ea5b3314bec0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4a940aa-aa99-459b-911a-7e2de75623ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Update_title</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f2ebbaae-fc04-4847-8195-cc1c0e9bcf29</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6a5b16c-7bac-479f-9b08-9b247b4826d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>415e3dd7-ce1f-4e73-8935-7b53ea5e6218</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f2ebbaae-fc04-4847-8195-cc1c0e9bcf29</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TitleName</value>
         <variableId>ef37cafc-1bdb-4388-816d-fd40c4f10b62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>248018ce-bbfc-47ae-b6dd-cefca1a86b36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Scripture</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>95006599-51d8-48d6-9c52-971db7b8f84c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dab7f456-542f-4071-a5c6-bbd3fe4f8427</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Update_decription</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4123eec1-1910-4f18-9c23-96a80f44f69b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4123eec1-1910-4f18-9c23-96a80f44f69b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DescptionText</value>
         <variableId>105922ca-418d-4d31-88cf-a73bb5fa6c5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bde1f76-a47f-45d5-a1ca-7147447cc6ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Update_keywords</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b9d8c7d7-21cc-4b0c-ae1f-b1e67dced26a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b9d8c7d7-21cc-4b0c-ae1f-b1e67dced26a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>KeywordsText</value>
         <variableId>d18270bf-b6ed-4a93-95cd-3537f6543b25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87737929-0312-4bfb-a447-82dc109c5782</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Update_vimeo_url</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ff353035-395b-450a-9fcb-f3c6f1a99d48</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ff353035-395b-450a-9fcb-f3c6f1a99d48</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>VimeoUrl</value>
         <variableId>95f4a2ce-99e1-4951-8223-ad86303a6163</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfe94313-97aa-4a45-be8e-26913326b0ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit_Media/TC_Upload_audio_file</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
