<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Edit_Series</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>fdf0ad95-2311-4155-8fa8-7d8efad0edba</testSuiteGuid>
   <testCaseLink>
      <guid>21939eba-e6d4-403e-91ea-105ab8a9b237</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_valid_creds</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a78a52c-11ab-432e-982a-c9740cbf0427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfdf9da2-de49-4845-9524-42a24b2cc088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02f7527c-85b4-40e0-b654-8c281ddff16e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc7be0ae-eb13-4240-8fb4-492cbc4b2b9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Edit_Media/Edit_series/TC_Update_series_series</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbfdbba3-222f-4040-903a-8f30416ce5a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8547d32-9432-408b-8be9-968924df3582</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eec12f3-8c08-46d6-b39c-8425d9e1a00f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20137963-cb81-459f-a443-3ae356298298</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit_Media/Edit_series/TC_Update_series_description</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>11fee659-2099-46dc-96bf-24b18b14b3c8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Edit_Media/TD_update_series</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>11fee659-2099-46dc-96bf-24b18b14b3c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Series Description</value>
         <variableId>e1b3cfaa-f9dd-47d0-b9b7-d14ae6b9a57e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
