<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>This suite contains all the test cases for valid test login</description>
   <name>Multiple_logins</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-18T07:03:52</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>338d1f51-c717-4648-a32d-b0bacbcd921c</testSuiteGuid>
   <testCaseLink>
      <guid>60d894d7-645b-493b-83d5-811ff16a979f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_invalid_creds</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>96d73453-e920-4931-b2d9-effaaac2b4f5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/TD_invalid_creds</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>818a8c5b-643c-4bac-a89e-141c29d1b0e1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/URL/url</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>818a8c5b-643c-4bac-a89e-141c29d1b0e1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>a031a349-e126-4048-ac42-edb2c885c7b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>96d73453-e920-4931-b2d9-effaaac2b4f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>1da9f9bb-030d-46ca-a162-863543234245</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>96d73453-e920-4931-b2d9-effaaac2b4f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a5f3af76-b786-4e5b-9354-9824c7d4d927</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a5b0636-b6ce-462d-be0d-ae92224496c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_valid_creds</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>33b6d63b-f8b9-4fa1-8c85-0bfa905685f4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/TD_valid_creds</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>6bc7241a-901a-4c8e-aa88-5fb6b779a2fa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/URL/url</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>6bc7241a-901a-4c8e-aa88-5fb6b779a2fa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>1a78a52c-11ab-432e-982a-c9740cbf0427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33b6d63b-f8b9-4fa1-8c85-0bfa905685f4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>cfdf9da2-de49-4845-9524-42a24b2cc088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33b6d63b-f8b9-4fa1-8c85-0bfa905685f4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>02f7527c-85b4-40e0-b654-8c281ddff16e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
